# Generated by Django 3.1.7 on 2021-04-26 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_account_category_spending_transfer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transfer',
            old_name='body',
            new_name='message',
        ),
    ]
