# Generated by Django 3.1.7 on 2021-05-01 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0007_user_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='user_budget',
            field=models.ManyToManyField(related_name='total_spending', to='budget.User_budget'),
        ),
        migrations.AlterField(
            model_name='user_budget',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_category', to='budget.category'),
        ),
    ]
