# Generated by Django 3.1.7 on 2021-05-01 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0008_auto_20210501_0354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='user_budget',
        ),
        migrations.AlterField(
            model_name='user_budget',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.category'),
        ),
    ]
